### ISSUE TITLE
Empty path to COM object

### ISSUE THREAD

**Issue by ElisScr** [PureRandom/VstsCoverCoverageExtension#5]
Using command prompt on the server I get the report I want, but when I am running dotcover analyze extension on VSTS I am getting 
"Failed to verify x64 COM object registration: Empty path to COM object." error.
According to this https://dotnettools-support.jetbrains.com/hc/en-us/community/posts/360000099870-DotCover-console-runner-fails-when-running-as-VSTS-task  I should add a new parameter "/CoreInstructionSet=[x86]" 
Any solution to this?

**Comment by PureRandom** [comment]
Hello,

I have updated the task to now include this setting, which after testing work!.

*[Commit  0408801](https://github.com/PureRandom/VstsCoverCoverageExtension/commit/0408801f75bd2016c6d1d8d8250f2aeb79811cd4) Update 0.3.3

Thanks for using and updating
