### ISSUE TITLE
How to publish report to VSTS for code coverage?

### ISSUE THREAD

**Issue by ossentoo** [PureRandom/VstsCoverCoverageExtension#6]
Hi,

thanks for this extension.

I am using this extension in a step in my build in VSTS.  However once created, it seems that the report is not usable for reporting the code coverage statistics within VSTS.  I receive an error when I use the Publish Test Results task:

 ##[warning]Failed to publish test results: Invalid file format.

I have tried all the different formats that can be outputted by dotcover- but it seems to me that none of the formats can be used.

So, how can either one of the formats that is outputed by dotcover be used in VSTS for reporting code coverage.  Alternatively, are there any converters that can be used to provide the same functionality?

regards

**Comment by PureRandom** [comment]
Hello, 

VSTS does not support DotCover to publish the Code Coverage results at the moment. From this thread below it seems have been requested but is not at the top of the list.
https://github.com/Microsoft/vsts-tasks/issues/2024

I am not sure how far they have got but the Agent Worker code is here:
https://github.com/Microsoft/vsts-agent/tree/master/src/Agent.Worker/CodeCoverage

A suggestion, not that it is super easy, would be to see how the supported reports are formatted, then once the DotCover report is made you can parse it into the correct format. This is in no way the best solution, but it might get things working.
https://docs.microsoft.com/en-us/vsts/pipelines/tasks/test/publish-code-coverage-results?view=vsts

If you do get any success with this, please send an update and I can look to built it into the task.

**Comment by ossentoo** [comment]
Great - thanks for the response. I'll give that a try.
